export const PINATA_API_KEY = process.env.NEXT_PUBLIC_PINATA_API_KEY;
export const PINATA_API_SECRET = process.env.NEXT_PUBLIC_PINATA_API_SECRET;

export const CONTRACT_ADDRESS_DAO = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_DAO;